clean:
        rm README.md
README.md:clean
        touch README.md
        echo "# Number of file Guessing game" > README.md
        echo "" >> README.md
        date >> README.md
        echo "" >> README.md
        cat guessinggame.sh | wc -l >> README.md
